import os
import re
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor

def add_paragraph_with_bold_runs(doc: Document, text: str, style: str = None):
    """
    Parses text containing **bold** inline tokens and appends formatted runs to the paragraph.
    """
    p = doc.add_paragraph(style=style) if style else doc.add_paragraph()
    # Split on **bold**
    tokens = re.split(r'(\*\*.*?\*\*)', text)
    for token in tokens:
        if not token:
            continue
        if token.startswith('**') and token.endswith('**') and len(token) >= 4:
            run = p.add_run(token[2:-2])
            run.bold = True
        else:
            p.add_run(token)
    return p

def generate_docx(title: str, content: str, output_path: str) -> str:
    """
    Generates a professionally formatted Microsoft Word (.docx) document from synthesized text.
    Handles headers, inline bold formatting, bullet lists, paragraph breaks, and confidentiality footer.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    doc = Document()

    # Document Title at the top
    title_p = doc.add_paragraph()
    title_run = title_p.add_run(title)
    title_run.font.size = Pt(20)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(24, 43, 73)  # Sovereign Navy
    title_p.paragraph_format.space_after = Pt(14)
    title_p.paragraph_format.space_before = Pt(6)

    # Confidentiality Footer on every page
    for section in doc.sections:
        footer = section.footer
        p_foot = footer.paragraphs[0]
        p_foot.text = "Generated by Sovereign On-Prem Agentic Workbench — Confidential"
        p_foot.alignment = WD_ALIGN_PARAGRAPH.CENTER
        if p_foot.runs:
            p_foot.runs[0].font.size = Pt(8.5)
            p_foot.runs[0].font.italic = True
            p_foot.runs[0].font.color.rgb = RGBColor(128, 128, 128)

    # Parse and format content
    lines = content.split('\n')
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if not line:
            i += 1
            continue

        # Skip horizontal dividers
        if line in ['---', '***', '___', '====', '----']:
            p = doc.add_paragraph()
            p.paragraph_format.space_after = Pt(4)
            i += 1
            continue

        # Markdown Headings (#, ##, ###, ####)
        if line.startswith('#'):
            level = len(line) - len(line.lstrip('#'))
            head_text = line.lstrip('#').strip()
            head_text = re.sub(r'\*\*(.*?)\*\*', r'\1', head_text)
            doc.add_heading(head_text, level=min(level, 3))
            i += 1
            continue

        # Bullet List Items (-, *, •)
        if (line.startswith(('-', '*', '•')) and len(line) > 1 and line[1] == ' '):
            bullet_text = line[2:].strip()
            add_paragraph_with_bold_runs(doc, bullet_text, style='List Bullet')
            i += 1
            continue

        # Numbered List Items (1., 2., etc.)
        num_match = re.match(r'^\d+\.\s+(.*)$', line)
        if num_match:
            num_text = num_match.group(1).strip()
            add_paragraph_with_bold_runs(doc, num_text, style='List Number')
            i += 1
            continue

        # Standalone short bold titles acting like section headers
        if (line.startswith('**') and line.endswith('**') and len(line) < 80):
            clean_head = line[2:-2].strip().rstrip(':')
            doc.add_heading(clean_head, level=2)
            i += 1
            continue

        # Regular paragraph with inline bold support
        add_paragraph_with_bold_runs(doc, line)
        i += 1

    doc.save(output_path)
    return output_path
